services:
  nginx:
    image: nginx:latest
    container_name: diploma_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../diploma-hotel:/var/www
    depends_on:
      - php
      - mysql

  # TODO: Remove docker dir from project or make it outside project just to rename containers

  php:
    container_name: diploma_php
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ../diploma-hotel:/var/www
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: diploma_db
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    container_name: diploma_redis
    image: redis:alpine
    ports:
      - "6379:6379"

  composer:
    container_name: diploma_composer
    image: composer:latest
    volumes:
      - .:/app
    command: composer install --ignore-platform-reqs
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: diploma_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: secret

volumes:
  mysqldata:
